### ISSUE TITLE
Premature media query matches

### ISSUE THREAD

**Issue by appreciated** [jcgueriaud/custom-media-query#5]
When adding a `CustomMediaQuery` as shown in the following example to a View, and the query matches at the beginning, the query will fire twice with different results at the beginning.

#### Code that was used
```
@Route("")
public class DetailDemoView2 extends HorizontalLayout {
    public DetailDemoView2() {
        CustomMediaQuery isViewVisible = new CustomMediaQuery(aBoolean -> setViewVisible(!aBoolean));
        isViewVisible.setQuery("(max-width: 600px)");
        getElement().appendChild(isViewVisible.getElement());
        add(isViewVisible);
    }

    private void setViewVisible(boolean b) {
        System.out.println("setViewVisible: " + b);
    }
}
```
Every time when reloading the same `@Route` the console always shows the following even though the page size did not change:

#### Console
```
setViewVisible: false
setViewVisible: true
```

**Comment by appreciated** [comment]
Possibly related [to the following line?](https://github.com/jcgueriaud/custom-media-query/blob/master/src/main/java/org/vaddon/CustomMediaQuery.java#L27)

**Comment by jcgueriaud** [comment]
Yes it's related to this line.
If I don't call getModel().setQuerymatches(true) (or false) then the event is not called the first time.

I'll check how I can change ths to avoid 2 calls on load.

**Comment by appreciated** [comment]
Maybe the solution is to update the serverside value manually from the client side as soon as the [Webcomponent is ready](https://polymer-library.polymer-project.org/2.0/docs/about_20#lifecycle-changes).

**Comment by jcgueriaud** [comment]
I've got an error when I do an update when the component is attached but I think it's linked to my usecase (I try hide or display a column of the grid and I've got a javascript error).

**Comment by appreciated** [comment]
Can you provide the error message?
> I think it's linked to my usecase

Does not really sound like that to me

**Comment by jcgueriaud** [comment]
You're right, it's not related to the grid.
I create a "simple demo view" and a branch: https://github.com/jcgueriaud/custom-media-query/tree/issue_5

If got this error "(TypeError) : Cannot read property 'a' of undefined" on the first load. If I understand it correctly, it's the "nullpointerexception" of Javascript, and I think it's inside the non-pretty Vaadin javascript.
It happens sometimes in chrome/chromium/Edge fo the simple view and everytime for the DemoView (with a grid).
I don't have this error in Firefox.

**Comment by jcgueriaud** [comment]
Thanks for your pull request
